# TODO: uncomment the 'backport 2.x' logic once the 2.x branch is cut from main
# backport 2.x:
#   - "*"
#   - "*/*"
#   - "*/**/*"
#   - "*/**/**/*"
#   - "*/**/**/**/*"
#   - "*/**/**/**/**/*"
#   - "*/**/**/**/**/**/*"
#   - "*/**/**/**/**/**/**/*"
#   - "*/**/**/**/**/**/**/**/*"
#   - "*/**/**/**/**/**/**/**/**/*"
#   - ".github/**/*"

infra:
  - ".github/**/*"
  - "build.gradle"
  - "build-tools/*"

documentation:
  - "*.md"
  - "release-notes/*"
  - "docs/*"
