backport 1.x:
  - "*"
  - "*/*"
  - "*/**/*"
  - "*/**/**/*"
  - "*/**/**/**/*"
  - "*/**/**/**/**/*"
  - "*/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/**/**/*"
  - ".github/**/*"

infra:
  - ".github/**/*"
  - "build.gradle"
  - "build-tools/*"

documentation:
  - "*.md"
  - "release-notes/*"
  - "docs/*"
