name: Build and Test ml-commons
# This workflow is triggered on pull requests and push to any branches
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Checkout ML
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -Dopensearch.version=1.3.0

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.3.0

      - name: Multi Nodes Integration Testing
        run: ./gradlew integTest  -PnumNodes=3

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
