name: Test MLCommons BWC
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Build-ad:
    strategy:
      matrix:
        java: [11,17]
      fail-fast: false

    name: Test MLCommons BWC
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # ml-commons
      - name: Checkout MLCommons
        uses: actions/checkout@v2

      - name: Assemble MLCommons
        run: |
          plugin_version=`./gradlew properties -q | grep "opensearch_build:" | awk '{print $2}'`
          echo plugin_version $plugin_version
          ./gradlew assemble
          echo "Creating ./plugin/src/test/resources/org/opensearch/ml/bwc..."
          mkdir -p ./plugin/src/test/resources/org/opensearch/ml/bwc
      - name: Run MLCommons Backwards Compatibility Tests
        run: |
          echo "Running backwards compatibility tests ..."
          ./gradlew bwcTestSuite -Dtests.security.manager=false